# Generated by Django 5.0.2 on 2024-02-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('chapter', models.IntegerField(choices=[(1, 'Chapter 1'), (2, 'Chapter 2'), (3, 'Chapter 3'), (4, 'Chapter 4'), (5, 'Chapter 5')])),
                ('video', models.FileField(upload_to='videos/')),
                ('short_details', models.TextField()),
            ],
        ),
    ]
