# Generated by Django 5.0.2 on 2024-02-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocontent',
            name='chapter',
            field=models.IntegerField(choices=[(1, 'Formulating the title'), (2, 'Crafting research questions'), (3, 'Creating introduction'), (4, 'Finding related literature'), (5, 'Presenting, analyzing, and interpreting data'), (6, 'Formulating conclusions and recommendations')]),
        ),
    ]
