# Generated by Django 5.0.2 on 2024-02-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0002_alter_videocontent_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=9, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
